apiVersion: apps/v1
kind: Deployment
metadata:
    name: rockynodeapps
    labels:
      app: rockynodeapp
spec:
    replicas: 3
    selector:
        matchLabels:
            app: rockynodeapp
    template:
        metadata:
            labels:
                app: rockynodeapp
        spec:
            containers:
                - name: rockynodeapp
                  image: rocky19devops/rockynodeapps:{{ .Values.env.APP_VERSION }}
                  ports:
                    - containerPort: 3000
                  env:
                  - name: NAME
                    value: 'rocky'
                  readinessProbe:
                    httpGet:
                        path: /health
                        port: 3000
                    initialDelaySeconds: 10
                    periodSeconds: 10
                    successThreshold: 1
                    failureThreshold: 3
                  livenessProbe:
                    httpGet:
                        path: /health
                        port: 3000
                    initialDelaySeconds: 10
                    periodSeconds: 10
                    timeoutSeconds: 5
                    successThreshold: 1
                    failureThreshold: 3
