apiVersion: v1
kind: Service
metadata:
  name: rockynodeservice
  labels:
    app: rockynodeapp
spec:
    type: NodePort
    selector:
        app: rockynodeapp
    ports:
     - protocol: TCP
       port: 3000
       targetPort: 3000
       nodePort: 30080
